import { useEffect, useState } from "react";
import { ImagePlus, Newspaper, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { uploadMedia, slugify } from "@/lib/media";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Post = { id: string; title: string; slug: string; excerpt: string; content: string; cover_url: string | null; published: boolean; created_at: string };
type Img = { id: string; url: string; caption: string };
const emptyPost = { id: "", title: "", excerpt: "", content: "", cover_url: null as string | null, published: true };

export function BlogAdmin() {
  const [posts, setPosts] = useState<Post[]>([]); const [form, setForm] = useState(emptyPost); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { const { data } = await supabase.from("blog_posts").select("*").order("created_at", { ascending: false }); setPosts(data ?? []); };
  useEffect(() => { load(); }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { let cover_url=form.cover_url; if(file) cover_url=await uploadMedia(file,"blog"); const row={title:form.title,excerpt:form.excerpt,content:form.content,published:form.published,cover_url}; const result=form.id?await supabase.from("blog_posts").update({...row,updated_at:new Date().toISOString()}).eq("id",form.id):await supabase.from("blog_posts").insert({...row,slug:`${slugify(form.title)}-${Date.now().toString(36)}`}); if(result.error)throw result.error; toast.success(form.id?"Post updated":"Post published"); setForm(emptyPost);setFile(null);await load(); }catch(error){toast.error((error as Error).message)} setBusy(false); };
  const remove=async(id:string)=>{if(!confirm("Delete this post?"))return;const{error}=await supabase.from("blog_posts").delete().eq("id",id);if(error)toast.error(error.message);else{toast.success("Post deleted");await load();}};
  return <div className="admin-content-grid"><form className="admin-panel admin-editor" onSubmit={save}><div className="admin-panel-head"><div><small>Editorial</small><h2>{form.id?"Edit article":"Write new article"}</h2></div><Newspaper/></div><label className="admin-field">Title<Input required value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label className="admin-field">Short introduction<Textarea rows={3} value={form.excerpt} onChange={(event)=>setForm({...form,excerpt:event.target.value})}/></label><label className="admin-field">Article text<Textarea className="admin-article-input" required rows={12} value={form.content} onChange={(event)=>setForm({...form,content:event.target.value})}/></label><label className="admin-field">Cover image<Input type="file" accept="image/*" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></label>{form.cover_url&&!file&&<img className="admin-cover-preview" src={form.cover_url} alt="Current cover"/>}<label className="admin-checkbox"><input type="checkbox" checked={form.published} onChange={(event)=>setForm({...form,published:event.target.checked})}/> Publish on website</label><div className="admin-actions"><Button disabled={busy}>{busy?"Saving…":form.id?"Save changes":"Publish article"}</Button>{form.id&&<Button type="button" variant="outline" onClick={()=>setForm(emptyPost)}>Cancel</Button>}</div></form><section className="admin-panel"><div className="admin-panel-head"><div><small>Content library</small><h2>All posts ({posts.length})</h2></div></div><div className="admin-content-list">{posts.map((post)=><article key={post.id}>{post.cover_url?<img src={post.cover_url} alt=""/>:<span/>}<div><b>{post.title}</b><small>{post.published?"Live":"Hidden"} · {new Date(post.created_at).toLocaleDateString("en-IN")}</small></div><Button aria-label={`Edit ${post.title}`} size="icon" variant="ghost" onClick={()=>setForm({id:post.id,title:post.title,excerpt:post.excerpt,content:post.content,cover_url:post.cover_url,published:post.published})}><Pencil/></Button><Button aria-label={`Delete ${post.title}`} size="icon" variant="ghost" onClick={()=>remove(post.id)}><Trash2/></Button></article>)}</div></section></div>;
}

export function GalleryAdmin() {
  const [items,setItems]=useState<Img[]>([]);const[files,setFiles]=useState<FileList|null>(null);const[caption,setCaption]=useState("");const[busy,setBusy]=useState(false);
  const load=async()=>{const{data}=await supabase.from("gallery_images").select("id,url,caption").order("created_at",{ascending:false});setItems(data??[])};useEffect(()=>{load()},[]);
  const upload=async(event:React.FormEvent)=>{event.preventDefault();if(!files?.length)return;setBusy(true);try{for(const file of Array.from(files)){const url=await uploadMedia(file,"gallery");const{error}=await supabase.from("gallery_images").insert({url,caption});if(error)throw error;}toast.success("Photos added to gallery");setCaption("");setFiles(null);(event.target as HTMLFormElement).reset();await load();}catch(error){toast.error((error as Error).message)}setBusy(false)};
  const remove=async(id:string)=>{if(!confirm("Delete this photo?"))return;const{error}=await supabase.from("gallery_images").delete().eq("id",id);if(error)toast.error(error.message);else await load()};
  return <div className="admin-stack"><form className="admin-panel admin-gallery-upload" onSubmit={upload}><span><ImagePlus/></span><div><small>Media library</small><h2>Add gallery photos</h2><p>Upload one or several images with an optional shared caption.</p></div><label className="admin-field">Photos<Input type="file" accept="image/*" multiple required onChange={(event)=>setFiles(event.target.files)}/></label><label className="admin-field">Caption<Input value={caption} onChange={(event)=>setCaption(event.target.value)}/></label><Button disabled={busy}><Plus/>{busy?"Uploading…":"Upload photos"}</Button></form><section className="admin-panel"><div className="admin-panel-head"><div><small>Published gallery</small><h2>{items.length} photos</h2></div></div><div className="admin-gallery-grid">{items.map((item)=><figure key={item.id}><img src={item.url} alt={item.caption}/><figcaption><span>{item.caption||"No caption"}</span><Button aria-label="Delete photo" variant="destructive" size="icon" onClick={()=>remove(item.id)}><Trash2/></Button></figcaption></figure>)}</div></section></div>;
}